function generate() {
	var r = document.getElementById("random");
	r.style.opacity = "0";
	setTimeout(() => {
		r.innerHTML = get_random([
			//
			"a potato flew around my room before you came.",
			"all around me are familiar faces, worn-out places, worn-out faces.",
			"all i wanted was for you to perform a couple hundred simple tests for a few years, and you couldn't even let me have that, could you?",
			"all my apes gone.",
			"all your base are belong to us.",
			"always know where your towel is.",
			"an eye for an eye makes the whole world blind.",
			"and then he turned himself into a pickle. funniest thing i've ever seen.",
			"and they were roommates.",
			"anybody on our side hiding any shocking and fantastic abilities they'd like to disclose? i'm open to suggestions.",
			"anything and everything, all of the time.",
			"apathy's a tragedy and boredom is a crime.",
			"as far as i'm concerned, that's america's ass.",
			"avengers, assemble.",
			//
			"back at it again at krispy kreme.",
			"bazinga.",
			"bears. beets. battlestar galactica.",
			"bond. james bond.",
			"bring out the holy hand grenade.",
			"but my lord, there is no such force.",
			"buying gf.",
			//
			"can i get a waffle? can i please get a waffle?",
			"chris, is that a weed? i'm calling the police.",
			"clever girl.",
			"could i interest you in everything all of the time?",
			//
			"death can have me when it earns me.",
			"do it. make your dreams come true. just do it.",
			"do or do not. there is no try.",
			"do you think god stays in heaven because he, too, lives in fear of what he's created?",
			"don't ever, for any reason, do anything, to anyone, for any reason, ever, no matter what, no matter where, or who, or who you are with, or where you are going, or where you've been, ever, for any reason whatsoever.",
			"don't make me tap the sign.",
			"dormammu, i've come to bargain.",
			"dude, you're embarrassing me in front of the wizards.",
			//
			"even if you did defeat me, what would you do then?",
			//
			"f to pay respects.",
			"fine, i'll do it myself.",
			"frankly, my dear, i don't give a damn.",
			"free stoof plox.",
			"friendship ended with mudasir, now salman is my best friend.",
			//
			"gaslight, gatekeep, girlboss.",
			"get to del taco, they got a new thing called fre shavoca do.",
			"git gud.",
			"go ahead, make my day.",
			"gotta catch 'em all.",
			//
			"happy christmas. it's christmas. merry crisis. merry chrysler.",
			"hasta la vista, baby.",
			"he was in the amazon with my mom when she was researching spiders just before she died.",
			"he's from space, he came here to steal a necklace from a wizard.",
			"he's not just a regular moron. he's the product of the greatest minds of a century working together with the express purpose of building the dumbest moron who ever lived.",
			"he's out of line, but he's right.",
			"help! help! i'm being repressed!",
			"here's looking at you, kid.",
			"hurricane katrina? more like hurricane tortilla.",
			//
			"i always come back.",
			"i always say, keep your friends rich and your enemies rich and wait to find out which is which.",
			"i am an architect.",
			"i am confusion. why is this one kansas but this one is not arkansas? america, explain. explain. what do you mean arkansas.",
			"i am groot.",
			"i am inevitable.",
			"i am iron man.",
			"i am once again asking for your financial support.",
			"i can has cheezburger?",
			"i can't believe you've done this.",
			"i declare bankruptcy.",
			"i don't care that you broke your elbow.",
			"i feel god in this chili's tonight.",
			"i have a question. for god. why?",
			"i have successfully privatized world peace.",
			"i have the power of god and anime on my side.",
			"i like trains.",
			"i like turtles.",
			"i must not fear. fear is the mind-killer. fear is the little-death that brings total obliteration.",
			"i never went to oovoo javer.",
			"i recognize the council has made a decision, but given that it's a stupid-ass decision, i've elected to ignore it.",
			"i see dead people.",
			"i see this as an absolute win.",
			"i spilled lipstick in your valentino bag.",
			"i told you, i don't want to join your super secret boy band.",
			"i understood that reference.",
			"i used the stones to destroy the stones.",
			"i wanna be a cowboy.",
			"i'll be back.",
			"i'll have two number nines, a number nine large, a number six with extra dip, a number seven, two number forty-fives, one with cheese, and a large soda.",
			"i'm a huge fan of the way you lose control and turn into an enormous green rage monster.",
			"i'm escaping to the one place that hasn't been corrupted by capitalism. space.",
			"i'm glad you asked that, because i wanted to take this time to explain my evil plan.",
			"i'm lovin' it.",
			"i'm not superstitious, but i am a little stitious.",
			"i'm slim shady, yes, i'm the real shady, all you other slim shadies are just imitating.",
			"i'm sorry, earth is closed today.",
			"i'm sorry, little one.",
			"i'm still worthy.",
			"i'm sure he died of natural causes. like a massive dragon or something.",
			"i'm the man who's gonna burn your house down with lemons!",
			"i've never met this man in my life.",
			"identity theft is not a joke, jim.",
			"if there are any spirits here tonight, tell me, does this sound like shakira?",
			"if you're nothing without the suit, then you shouldn't have it.",
			"iridocyclitis.",
			"is this a pigeon?",
			"is this the real life? is this just fantasy?",
			"it is pitch black. you are likely to be eaten by a grue.",
			"it is wednesday, my dudes.",
			"it was a pleasure to burn.",
			"it was a pleasure to burn. it was a special pleasure to see things eaten, to see things blackened and changed.",
			"it's a simple spell, but quite unbreakable.",
			"it's free real estate.",
			"it's morbin' time.",
			"it's not calibrated to someone of your... generous... ness.",
			"it's not out of the question that you might have a very minor case of serious brain damage.",
			"it's over nine thousand.",
			"it's the most beautiful thing i've ever seen in my life. it's a banana next to a banana.",
			//
			"life is like a box of chocolates. you never know what you're gonna get.",
			"like a red cape, but blue.",
			"look at all those chickens.",
			"look at this graph.",
			"look at you soaring through the air, like an eagle piloting a blimp.",
			"look on my works, ye mighty, and despair.",
			//
			"mary, is that a police? i'm calling the weed.",
			"mmm whatcha say, that you only meant well?",
			"mr. stark, i don't feel so good.",
			//
			"never gonna give you up, never gonna let you down.",
			"never interrupt your enemy when he is making a mistake.",
			"never let mod timbo near a thing of beauty.",
			"nice argument, but as you can see, i have already drawn you as the soyjack and myself as the chad.",
			"no off topic questions. because i don't want to. no. no. permission denied. that's an off topic question. next. you have been stopped.",
			"nobody expects the spanish inquisition.",
			"nothing interesting happens.",
			"now i am become death, destroyer of worlds.",
			"now that is an avengers-level threat.",
			//
			"oh hi, thanks for checking in, i'm still a piece of garbage.",
			"oh my god, they were roommates.",
			"oh, hi. so, how are you holding up? because i'm a potato.",
			"on your left.",
			"one does not simply walk into mordor.",
			//
			"perfectly balanced, as all things should be.",
			"pokemon go to the polls.",
			//
			"reality can be whatever i want.",
			"road work ahead? yeah, i sure hope it does.",
			//
			"sabra gives you all your daily nutrients, like zero grams of trans fat, and oh my god cholesterol.",
			"shaken, not stirred.",
			"silence, brand.",
			"skill issue.",
			"so no head?",
			"so, how are you holding up? because i'm a potato.",
			"sometimes i'll start a sentence and i don't even know where it's going. i just hope i find it along the way.",
			"stand in the ashes of a trillion dead souls, and ask the ghosts if honor matters.",
			"stop examining signs, you're in the wilderness now!",
			"stop, i coulda dropped my croissant.",
			"strange women lying in ponds distributing swords is no basis for a system of government.",
			//
			"'tis but a scratch.",
			"that jumpsuit you're wearing looks stupid. that's not me talking; it's right here in your file.",
			"that man has no regard for lawn maintenance.",
			"that man is playing galaga. thought we wouldn't notice.",
			"that's no ordinary rabbit.",
			"that's what she said.",
			"the cake is a lie.",
			"the hardest choices require the strongest wills.",
			"the most versatile substance on the planet, and they used it to make a frisbee.",
			"the power of christ compels you.",
			"the weighted companion cube will never threaten to stab you, and, in fact, cannot speak.",
			"they ask you how you are and you just have to say that you're fine, and you're not really fine but you just can't get into it.",
			"they asked me how well i understood theoretical physics. i said i had a theoretical degree in physics. they said welcome aboard.",
			"this is a potion bottle, not a klein bottle.",
			"this is fine.",
			"this is my impression of when shakira goes to wash her hands but the water's too hot. thank you.",
			"this is the dollar store, how good can it be?",
			"this is the most beautiful thing i've ever seen in my life. it's watermelon inside a watermelon.",
			"this is the part where he kills you.",
			"this is the way.",
			"this too shall pass.",
			"this was a triumph. i'm making a note here, huge success.",
			"to be fair, you have to have a very high IQ to understand rick and morty.",
			"to be fair, you have to have a very high IQ to understand rick and morty. the humor is extremely subtle, and without a solid grasp of theoretical physics most of the jokes will go over a typical viewer's head.",
			"to become god is the loneliest achievement of them all.",
			"tony stark was able to build this in a cave, with a box of scraps.",
			//
			"violence for violence is the rule of beasts.",
			//
			"wait, that's illegal.",
			"wait, why does johnny have so many soaps?",
			"we don't do that here.",
			"we just got the results from that last test: you are a horrible person. that's what it says. a horrible person. we weren't even testing for that.",
			"we're not in kansas anymore.",
			"we've both said a lot of things that you're going to regret.",
			"welcome to chili's.",
			"welcome to the hotel california.",
			"welcome to the internet.",
			"well, when life gives you lemons...",
			"what are those?",
			"what goes around, comes around.",
			"what is a man? a miserable little pile of secrets.",
			"what is the airspeed velocity of an unladen swallow?",
			"when life gives you lemons, don't make lemonade - make life take the lemons back! get mad! i don't want your damn lemons!",
			"when the earth starts to settle, god throws a stone at it. and believe me, he's winding up.",
			"when will you learn? when will you learn that your actions have consequences?",
			"where is gamora?",
			"where's the beef?",
			"why are you running? why are you running?",
			"why does johnny have so many soaps?",
			"will the real slim shady please stand up?",
			"with great power comes great responsibility.",
			"won't the real slim shady please stand up?",
			"would i rather be feared or loved? easy. both. i want people to be afraid of how much they love me.",
			//
			"x to doubt.",
			//
			"you can't handle the truth.",
			"you could not live with your own failure. where did that bring you? back to me.",
			"you guys are getting paid?",
			"you know, i'm something of a scientist myself.",
			"you like jazz?",
			"you might have a very minor case of serious brain damage.",
			"you must construct additional pylons.",
			"you're going to need a bigger boat.",
			"you're the spider...ling. crime fighting spider. spider boy?",
			"your mother was a hamster and your father smelt of elderberries.",
		]);
		r.style.opacity = "1";
	}, 500);
}