function generate() {
	var r = document.getElementById("random");
	r.style.opacity = "0";
	setTimeout(() => {
		r.innerHTML = get_random([
			//
			"a potato flew around my room before you came.",
			"all my apes gone.",
			"all your base are belong to us.",
			"always know where your towel is.",
			"an eye for an eye makes the whole world blind.",
			"and they were roommates.",
			"anybody on our side hiding any shocking and fantastic abilities they'd like to disclose? i'm open to suggestions.",
			"anything and everything, all of the time.",
			"apathy's a tragedy and boredom is a crime.",
			"as far as i'm concerned, that's america's ass.",
			"avengers, assemble.",
			//
			"back at it again at krispy kreme.",
			"bazinga.",
			"bond. james bond.",
			"but my lord, there is no such force.",
			"buying gf.",
			//
			"chris, is that a weed? i'm calling the police.",
			"clever girl.",
			"could i interest you in everything all of the time?",
			//
			"do you think god stays in heaven because he, too, lives in fear of what he's created?",
			"don't make me tap the sign.",
			"dormammu, i've come to bargain.",
			"dude, you're embarrassing me in front of the wizards.",
			//
			"even if you did defeat me, what would you do then?",
			//
			"f to pay respects.",
			"fine, i'll do it myself.",
			"frankly, my dear, i don't give a damn.",
			"free stoof plox.",
			"friendship ended with mudasir, now salman is my best friend.",
			//
			"gaslight, gatekeep, girlboss.",
			"get to del taco, they got a new thing called fre shavoca do.",
			"go ahead, make my day.",
			"gotta catch 'em all.",
			//
			"happy christmas. it's christmas. merry crisis. merry chrysler.",
			"hasta la vista, baby.",
			"he's from space, he came here to steal a necklace from a wizard.",
			"he's out of line, but he's right.",
			"here's looking at you, kid.",
			"hurricane katrina? more like hurricane tortilla.",
			//
			"i always come back.",
			"i always say, keep your friends rich and your enemies rich and wait to find out which is which.",
			"i am an architect.",
			"i am confusion. why is this one kansas but this one is not arkansas? america, explain. explain. what do you mean arkansas.",
			"i am groot.",
			"i am inevitable.",
			"i am iron man.",
			"i am once again asking for your financial support.",
			"i can has cheezburger?",
			"i can't believe you've done this.",
			"i feel god in this chili's tonight.",
			"i have a question. for god. why?",
			"i have successfully privatized world peace.",
			"i like trains.",
			"i like turtles.",
			"i must not fear. fear is the mind-killer. fear is the little-death that brings total obliteration.",
			"i never went to oovoo javer.",
			"i recognize the council has made a decision, but given that it's a stupid-ass decision, i've elected to ignore it.",
			"i see dead people.",
			"i see this as an absolute win.",
			"i told you, i don't want to join your super secret boy band.",
			"i understood that reference.",
			"i used the stones to destroy the stones.",
			"i wanna be a cowboy.",
			"i'll be back.",
			"i'll have two number nines, a number nine large, a number six with extra dip, a number seven, two number forty-fives, one with cheese, and a large soda.",
			"i'm a huge fan of the way you lose control and turn into an enormous green rage monster.",
			"i'm escaping to the one place that hasn't been corrupted by capitalism. space.",
			"i'm glad you asked that, because i wanted to take this time to explain my evil plan.",
			"i'm lovin' it.",
			"i'm slim shady, yes, i'm the real shady, all you other slim shadies are just imitating.",
			"i'm sorry, earth is closed today.",
			"i'm sorry, little one.",
			"i'm still worthy.",
			"i'm sure he died of natural causes. like a massive dragon or something.",
			"i'm the man who's gonna burn your house down with lemons!",
			"i've never met this man in my life.",
			"if you're nothing without the suit, then you shouldn't have it.",
			"iridocyclitis.",
			"is this a pigeon?",
			"is this the real life? is this just fantasy?",
			"it is pitch black. you are likely to be eaten by a grue.",
			"it is wednesday my dudes.",
			"it's a simple spell, but quite unbreakable.",
			"it's free real estate.",
			"it's morbin' time.",
			"it's not out of the question that you might have a very minor case of serious brain damage.",
			"it's over nine thousand.",
			//
			"life is like a box of chocolates. you never know what you're gonna get.",
			"like a red cape, but blue.",
			"look at all those chickens.",
			"look on my works, ye mighty, and despair.",
			//
			"mary, is that a police? i'm calling the weed.",
			"mr. stark, i don't feel so good.",
			//
			"never interrupt your enemy when he is making a mistake.",
			"never let mod timbo near a thing of beauty.",
			"nice argument, but as you can see, i have already drawn you as the soyjack and myself as the chad.",
			"no off topic questions. because i don't want to. no. no. permission denied. that's an off topic question. next. you have been stopped.",
			"nothing interesting happens.",
			"now i am become death, destroyer of worlds.",
			"now that is an avengers-level threat.",
			//
			"oh hi, thanks for checking in, i'm still a piece of garbage.",
			"oh my god, they were roommates.",
			"oh, hi. so, how are you holding up? because i'm a potato.",
			"on your left.",
			"one does not simply walk into mordor.",
			//
			"perfectly balanced, as all things should be.",
			"pokemon go to the polls.",
			//
			"reality can be whatever i want.",
			"road work ahead? yeah, i sure hope it does.",
			//
			"shaken, not stirred.",
			"silence, brand.",
			"skill issue.",
			"so, how are you holding up? because i'm a potato.",
			"stop examining signs, you're in the wilderness now!",
			"stop, i coulda dropped my croissant.",
			//
			"that man has no regard for lawn maintenance.",
			"that man is playing galaga. thought we wouldn't notice.",
			"that's what she said.",
			"the cake is a lie.",
			"the hardest choices require the strongest wills.",
			"the most versatile substance on the planet, and they used it to make a frisbee.",
			"the power of christ compels you.",
			"the weighted companion cube will never threaten to stab you, and, in fact, cannot speak.",
			"they ask you how you are and you just have to say that you're fine, and you're not really fine but you just can't get into it.",
			"this is a potion bottle, not a klein bottle.",
			"this is fine.",
			"this is the dollar store, how good can it be?",
			"this is the way.",
			"this too shall pass.",
			"this was a triumph. i'm making a note here, huge success.",
			"to become god is the loneliest achievement of them all.",
			"tony stark was able to build this in a cave, with a box of scraps.",
			//
			"violence for violence is the rule of beasts.",
			//
			"wait, that's illegal.",
			"we don't do that here.",
			"we're not in kansas anymore.",
			"welcome to chili's.",
			"welcome to the internet.",
			"well, when life gives you lemons...",
			"what are those?",
			"what is a man? a miserable little pile of secrets.",
			"when life gives you lemons, don't make lemonade - make life take the lemons back! get mad! i don't want your damn lemons!",
			"when the earth starts to settle, god throws a stone at it. and believe me, he's winding up.",
			"when will you learn? when will you learn that your actions have consequences?",
			"where is gamora?",
			"where's the beef?",
			"why are you running? why are you running?",
			"will the real slim shady please stand up?",
			"with great power comes great responsibility.",
			"won't the real slim shady please stand up?",
			//
			"x to doubt.",
			//
			"you can't handle the truth.",
			"you could not live with your own failure. where did that bring you? back to me.",
			"you guys are getting paid?",
			"you know, i'm something of a scientist myself.",
			"you like jazz?",
			"you might have a very minor case of serious brain damage.",
			"you must construct additional pylons.",
			"you're going to need a bigger boat.",
			"you're the spider...ling. crime fighting spider. spider boy?",
		]);
		r.style.opacity = "1";
	}, 500);
}